// <auto-generated />
using BookProject.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookProject.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("BookProject.Api.Data.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Jane Austen",
                            Price = 180.0,
                            Title = "Gurur ve ÖnYargı"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Jack London",
                            Price = 125.0,
                            Title = "Martin Eden"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Jack London",
                            Price = 45.0,
                            Title = "Beyaz Diş"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Daniel Defoe",
                            Price = 330.0,
                            Title = "Kaptan Singleton"
                        },
                        new
                        {
                            Id = 5,
                            Author = "William Golding",
                            Price = 384.0,
                            Title = "Akrep Kral"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Graham Greene",
                            Price = 560.0,
                            Title = "İstanbul Treni"
                        },
                        new
                        {
                            Id = 7,
                            Author = "William Shakespeare",
                            Price = 300.0,
                            Title = "Macbeth"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
